name: AppleTranslateTool
options:
  bundleIdPrefix: com.magictoolbox
  deploymentTarget:
    macOS: "14.4"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.4"

targets:
  AppleTranslateTool:
    type: tool
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_NAME: AppleTranslateTool-bin
        INFOPLIST_FILE: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"